name: photodirs_prod
services:
  nginx:
    image: nginx:1
    depends_on:
      - frontend
      - api
    ports:
      - '3333:3333'
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - prod_cache:/cache:ro

  frontend:
    build:
      context: ./frontend
      target: prod
    environment:
      NODE_ENV: production
    restart: unless-stopped

  api:
    build:
      context: ./backend
      target: prod
    environment:
      NODE_ENV: production
    restart: unless-stopped
    volumes:
      - prod_albums:/albums:ro
      - prod_cache:/cache

  watcher:
    build:
      context: ./backend
      target: prod
    environment:
      NODE_ENV: production
    restart: unless-stopped
    command: "npm run start:watcher"
    volumes:
      - prod_albums:/albums:ro
      - prod_cache:/cache

volumes:
  prod_albums:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=truenas.lan,vers=4,soft,nolock"
      device: ":/mnt/data-pool/shared/photos"
  prod_cache:
