services:
  nginx:
    image: nginx:1
    depends_on:
      - frontend
      - api
    ports:
      - '3333:3333'
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build: ./frontend
    environment:
      WDS_SOCKET_PORT: 0
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  api:
    build: ./api
    environment:
      TERM: xterm
    restart: unless-stopped
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
      - ./api/test-images:/albums
      - cache:/cache

volumes:
  api_node_modules:
  frontend_node_modules:
  cache:
