services:
  nginx:
    image: nginx:1
    depends_on:
      - frontend
      - api
    ports:
      - '3333:3333'
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro

  frontend:
    build:
      context: ../frontend
      target: dev
    environment:
      WDS_SOCKET_PORT: 0
    restart: unless-stopped
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules

  api:
    build:
      context: ../api
      target: dev
    environment:
      TERM: xterm
    restart: unless-stopped
    volumes:
      - ../api:/app
      - api_node_modules:/app/node_modules
      - ../test-album:/albums:ro
      - dev_cache:/cache

volumes:
  api_node_modules:
  frontend_node_modules:
  dev_cache:
