name: photodirs_imgs
services:
  nginx:
    image: ghcr.io/zsteinkamp/photodirs-nginx
    depends_on:
      - frontend
      - api
      - admin
    ports:
      - '8333:3333'
      - '9333:4333'
    restart: unless-stopped
    volumes:
      - prod_cache:/cache:ro

  frontend:
    image: ghcr.io/zsteinkamp/photodirs-frontend
    restart: unless-stopped

  api:
    image: ghcr.io/zsteinkamp/photodirs-api
    restart: unless-stopped
    volumes:
      - prod_cache:/cache
      - prod_albums:/albums:ro

  watcher:
    image: ghcr.io/zsteinkamp/photodirs-api
    restart: unless-stopped
    volumes:
      - prod_cache:/cache
      - prod_albums:/albums:ro
  admin:
    image: ghcr.io/zsteinkamp/photodirs-admin
    restart: unless-stopped
    volumes:
      - prod_cache:/cache
      - prod_albums:/albums:rw
volumes:
  prod_cache:
  prod_albums:
    driver: local
    driver_opts:
      type: 'nfs'
      o: 'addr=truenas.lan,nfsvers=4,soft,nolock'
      device: ':/mnt/data-pool/shared/photos/zzz_blog_images'
