name: photodirs_dev
services:
  nginx:
    image: nginx:1
    depends_on:
      - frontend
      - api
    ports:
      - '4444:3333'
    stop_signal: SIGKILL
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - dev_cache:/cache:ro

  frontend:
    build:
      context: ../frontend
      target: dev
    environment:
      WDS_SOCKET_PORT: 0
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules

  api:
    build:
      context: ../backend
      target: dev
    command: "npm run watch:api"
    environment:
      TERM: xterm
    volumes:
      - ../backend:/app
      - api_node_modules:/app/node_modules
      - ../test-album:/albums:ro
      - dev_cache:/cache

  watcher:
    build:
      context: ../backend
      target: dev
    command: "npm run watch:watcher"
    environment:
      TERM: xterm
    volumes:
      - ../backend:/app
      - api_node_modules:/app/node_modules
      - ../test-album:/albums:ro
      - dev_cache:/cache

volumes:
  api_node_modules:
  frontend_node_modules:
  dev_cache:
