services:
  nginx:
    image: nginx:1
    depends_on:
      - frontend
      - api
    ports:
      - '3333:3333'
    restart: unless-stopped
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: ../frontend
      target: prod
    environment:
      NODE_ENV: production
    restart: unless-stopped

  api:
    build:
      context: ../api
      target: prod
    restart: unless-stopped
    volumes:
      - /mnt/shared/photos:/albums:ro
      - prod_cache:/cache

volumes:
  prod_cache:
